pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                git branch: 'main', url: 'https://github.com/jbravo1996/springrest/'
                sh '''cd restservice
                    ./gradlew test assemble'''
            }
            post {
                success {
                    junit 'restservice/build/test-results/test/*.xml'
                    archiveArtifacts artifacts: 'restservice/build/libs/*.jar', fingerprint:true, followSymlinks:false
                }
            }
        }
    }
}
