pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                //git branch: 'main', url: 'https://github.com/jbravo1996/springrest/'
                withGradle {
                    sh '''cd restservice
                    ./gradlew test assemble'''
                }              
            }
            post {
                success {
                    junit 'restservice/build/test-results/test/*.xml'
                    archiveArtifacts artifacts: 'restservice/build/libs/*.jar', fingerprint:true, followSymlinks:false
                }
            }
        }
        stage('Publish'){
            steps{
                sshagent(['ssh-gitkey']) {
                            sh 'git tag BUILD-1.0.${BUILD_NUMBER}'
                            sh 'git push --tags'
                }
            }
        }
    }
}
